[package]
name = "databend-common-exception"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
databend-common-arrow = { workspace = true }
databend-common-ast = { workspace = true }

anyhow = { workspace = true }
arrow-flight = { workspace = true }
arrow-schema = { workspace = true }
backtrace = { workspace = true, features = ["std", "serialize-serde"] }
bincode = { workspace = true }
geos = { workspace = true }
geozero = { workspace = true }
gimli = { workspace = true }
http = { workspace = true }
libc = { workspace = true }
object = { workspace = true }
once_cell = { workspace = true }
opendal = { workspace = true }
parquet = { workspace = true }
paste = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true }
rustc-demangle = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tantivy = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["geos"]

[lints]
workspace = true
